services:
  - type: web
    name: portfolio-tracker
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FINNHUB_API_KEY
        sync: false
      - key: EXCHANGE_RATE_API_KEY
        sync: false